version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: redis
  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    env_file:
     - '.env' 
    command: bundle exec sidekiq
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "8093:3000"
    depends_on:
      - db
      - redis
    volumes:
      - '.:/usr/src/app'
    env_file:
      - '.env' 

    
